Added event to queue that listened by desk service and print in logs
kanwalnainsingh/OpenDesk pull request #128
Opened 2020-12-17 02:43 UTC by mayralgr

Closes #106 
[ ] Add sender to OrganisationService
[ ] Queue request in rabbitmq
[ ] Add listener to desk service 
[ ] Print in log

2020-12-17 10:40 UTC, kanwalnainsingh commented
@mayralgr build is failing with your change can you check. https://github.com/kanwalnainsingh/OpenDesk/pull/128/checks?check_run_id=1567866570

2020-12-17 13:19 UTC, kanwalnainsingh requested changes
Build is failing need fix.

2020-12-17 14:14 UTC, mayralgr commented
Hi @kanwalnainsingh yes, I'll take a look at the build, the PR is still a work in progress so I let it as a draft for now and let you know when is ready for review 
Thank you!

2020-12-17 14:15 UTC, kanwalnainsingh commented
Sure, thanks a lot 😊

2020-12-18 01:43 UTC, mayralgr commented
@kanwalnainsingh one doubt, a profile should be considered like in kafka?
```Java
@Configuration
@Profile("local")
public class KafkaConfig {
.....
```
or is not necessary?

2020-12-18 02:45 UTC, kanwalnainsingh commented
@mayralgr can you create a dev profile and use it.

2020-12-18 03:02 UTC, mayralgr commented
@kanwalnainsingh okay, I left the dev profile for good or just for develop? Also, can you give me some feedback. It is just adding the event queue, or this issue also covers the listening in the desk service.
Thanks!

2020-12-18 03:08 UTC, kanwalnainsingh commented
I will review today and let you know.

2020-12-19 17:23 UTC, mayralgr commented
@kanwalnainsingh let me know if you have had time to check it and if any changes are required 😄

2020-12-19 17:37 UTC, kanwalnainsingh commented
> @kanwalnainsingh let me know if you have had time to check it and if any changes are required 😄

checking now, thanks for reminder :)

2020-12-19 17:38 UTC, kanwalnainsingh approved these changes
Changes looks good, merging. Thanks alot, let me know if you would like to pick something else too.

2020-12-19 18:19 UTC, merged