Organization employees page
kanwalnainsingh/OpenDesk pull request #139
Opened 2020-12-21 21:17 UTC by mayralgr

Closes #118 
[ X ] NavBar
[ X ] Desktop Version
[ ] Mobile Version

based on: [Figma file](https://www.figma.com/file/NihC7mPNWDLTTfOyKpChhN/BookOpendesk?node-id=3%3A1530)

**Screenshots**
Current state:

**Desktop version**
<img width="900" alt="Screen Shot 2020-12-21 at 15 15 09" src="https://user-images.githubusercontent.com/16580567/102822783-529fd680-439f-11eb-8b1d-6de075484080.png">

**Mobile version in progress**

This work is still in progress, pull request draft opened for feedback.

2020-12-22 07:50 UTC, kanwalnainsingh approved these changes

2020-12-22 07:53 UTC, kanwalnainsingh commented
@mayralgr there are merge conflicts that need fix.

2020-12-22 07:53 UTC, kanwalnainsingh requested changes
merge conflicts

2020-12-22 22:13 UTC, mayralgr commented
@kanwalnainsingh I think is done, I solved the conflicts, let me know if anything needs to be changed or if something is missing.
Thank you!

2020-12-23 18:47 UTC, kanwalnainsingh approved these changes

2020-12-23 19:07 UTC, merged